In [149]:
import random 
import numpy as np
# Знайти в датасеті таргет. Завантажити датасет без таргета
data = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0, 1, 2, 3))
print(data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [150]:
# Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)
print(data.ndim)
print(data.shape)

2
(150, 4)


In [151]:
# Порахувати mean, median, standard deviation для 1-ї колонки
col_1 = data[:, 0]
print("Mean: ", np.mean(col_1))
print("Median: ", np.median(col_1))
print("Standard deviation: ", np.std(col_1))

Mean:  5.843333333333334
Median:  5.8
Standard deviation:  0.8253012917851409


In [152]:
"""Вставити 20 значень np.nan на випадкові позиції в масиві 
(при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)"""
# data = data.flatten()
# random.seed(42)
# rand_num = random.sample(range(len(data)), 20)
# data[rand_num] = np.nan # Перше, що спало на думку
# data = data.reshape(150, 4)
# data
np.random.seed(17)
indices = np.random.choice(len(data.flat), size=20, replace=False)
data.flat[indices] = np.nan
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , nan, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, nan, nan],
       [4.9, 3

In [153]:
# Знайти позиції вставлених значень np.nan в 1-й колонці
col_1_new = data[:, 0]
print(col_1_new)
np.where(np.isnan(col_1_new))

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 nan 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 nan 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 nan 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 nan 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 nan 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


(array([ 74,  96, 109, 123, 132]),)

In [154]:
# Замінити всі значення np.nan на 0
data[np.where(np.isnan(data))] = 0
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 0. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 0. , 0. ],
       [4.9, 3

In [155]:
# Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)
data_filtered = data[(data[:, 0] < 5) & (data[:, 2] > 1.5)]
data_filtered

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [0. , 2.9, 4.3, 1.3],
       [0. , 0. , 4.2, 1.3],
       [4.9, 2.5, 4.5, 1.7],
       [0. , 3.6, 6.1, 2.5],
       [0. , 2.7, 4.9, 0. ]])

In [156]:
# Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)
data_1, data_2 = np.split(data, 2)
print(data_1)
print(data_2)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  0.  0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 0.  0. ]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [157]:
# Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням
data_1[:, 0].sort()
data_2[:, 0].sort(descending=True)
print(data_1)
print(data_2)

[[0.  3.5 1.4 0.2]
 [4.3 3.  1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.1 1.5 0.2]
 [4.4 3.6 1.4 0.2]
 [4.5 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [4.6 3.4 1.5 0.2]
 [4.6 2.9 1.4 0.2]
 [4.6 3.1 1.5 0.1]
 [4.7 3.7 1.5 0.2]
 [4.7 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.  1.1 0.1]
 [4.8 4.  0.  0.2]
 [4.8 4.4 1.5 0.4]
 [4.8 3.9 1.3 0.4]
 [4.9 3.5 1.4 0.3]
 [4.9 3.8 1.7 0.3]
 [4.9 3.8 1.5 0.3]
 [4.9 3.4 1.7 0.2]
 [4.9 3.7 1.5 0.4]
 [5.  3.6 1.  0.2]
 [5.  3.3 1.7 0.5]
 [5.  3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.5 0.2]
 [5.  3.4 1.4 0.2]
 [5.  3.2 1.6 0.2]
 [5.  3.1 1.6 0.2]
 [5.1 3.4 1.5 0.4]
 [5.1 4.1 1.5 0.1]
 [5.1 4.2 0.  0. ]
 [5.1 3.1 1.5 0.1]
 [5.1 3.2 1.2 0.2]
 [5.1 3.5 1.3 0.2]
 [5.1 3.1 1.5 0.1]
 [5.1 3.  1.3 0.2]
 [5.2 3.4 1.5 0.2]
 [5.2 3.5 1.3 0.3]
 [5.2 2.3 1.3 0.3]
 [5.2 3.2 1.3 0.2]
 [5.3 3.5 1.6 0.6]
 [5.4 3.8 1.9 0.4]
 [5.4 3.  1.4 0.3]
 [5.4 3.8 1.6 0.2]
 [5.4 3.2 1.4 0.2]
 [5.4 3.7 1.5 0.2]
 [5.5 3.3 1.4 0.2]
 [5.5 3.2 4.7 1.4]
 [5.5 3.2 4.5 1.5]
 [5.6 3.1 4.

In [158]:
# Зібрати обидва массиви в одне ціле
data_combined = np.concatenate([data_1, data_2], axis=0)
data_combined

array([[0. , 3.5, 1.4, 0.2],
       [4.3, 3. , 1.4, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 3.1, 1.5, 0.2],
       [4.4, 3.6, 1.4, 0.2],
       [4.5, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.4, 1.5, 0.2],
       [4.6, 2.9, 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.1],
       [4.7, 3.7, 1.5, 0.2],
       [4.7, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3. , 1.1, 0.1],
       [4.8, 4. , 0. , 0.2],
       [4.8, 4.4, 1.5, 0.4],
       [4.8, 3.9, 1.3, 0.4],
       [4.9, 3.5, 1.4, 0.3],
       [4.9, 3.8, 1.7, 0.3],
       [4.9, 3.8, 1.5, 0.3],
       [4.9, 3.4, 1.7, 0.2],
       [4.9, 3.7, 1.5, 0.4],
       [5. , 3.6, 1. , 0.2],
       [5. , 3.3, 1.7, 0.5],
       [5. , 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.5, 0.2],
       [5. , 3.4, 1.4, 0.2],
       [5. , 3.2, 1.6, 0.2],
       [5. , 3.1, 1.6, 0.2],
       [5.1, 3.4, 1.5, 0.4],
       [5.1, 4.1, 1.5, 0.1],
       [5.1, 4.2, 0. , 0. ],
       [5.1, 3

In [159]:
# Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю
uniqs, count = np.unique(data_combined, return_counts=True)
print(np.dstack((uniqs, count)))

[[[ 0.  20. ]
  [ 0.1  6. ]
  [ 0.2 27. ]
  [ 0.3  7. ]
  [ 0.4  7. ]
  [ 0.5  1. ]
  [ 0.6  1. ]
  [ 1.   8. ]
  [ 1.1  4. ]
  [ 1.2  6. ]
  [ 1.3 20. ]
  [ 1.4 19. ]
  [ 1.5 26. ]
  [ 1.6 11. ]
  [ 1.7  6. ]
  [ 1.8 11. ]
  [ 1.9  7. ]
  [ 2.   7. ]
  [ 2.1  6. ]
  [ 2.2  4. ]
  [ 2.3 12. ]
  [ 2.4  6. ]
  [ 2.5 10. ]
  [ 2.6  5. ]
  [ 2.7  9. ]
  [ 2.8 14. ]
  [ 2.9  9. ]
  [ 3.  25. ]
  [ 3.1 11. ]
  [ 3.2 13. ]
  [ 3.3  7. ]
  [ 3.4 12. ]
  [ 3.5  8. ]
  [ 3.6  4. ]
  [ 3.7  4. ]
  [ 3.8  7. ]
  [ 3.9  5. ]
  [ 4.   4. ]
  [ 4.1  4. ]
  [ 4.2  5. ]
  [ 4.3  3. ]
  [ 4.4  8. ]
  [ 4.5  9. ]
  [ 4.6  7. ]
  [ 4.7  7. ]
  [ 4.8  9. ]
  [ 4.9 11. ]
  [ 5.  14. ]
  [ 5.1 17. ]
  [ 5.2  6. ]
  [ 5.3  3. ]
  [ 5.4  8. ]
  [ 5.5 10. ]
  [ 5.6 11. ]
  [ 5.7 10. ]
  [ 5.8 10. ]
  [ 5.9  5. ]
  [ 6.   8. ]
  [ 6.1  9. ]
  [ 6.2  4. ]
  [ 6.3  9. ]
  [ 6.4  6. ]
  [ 6.5  5. ]
  [ 6.6  3. ]
  [ 6.7 10. ]
  [ 6.8  3. ]
  [ 6.9  5. ]
  [ 7.   1. ]
  [ 7.1  1. ]
  [ 7.2  2. ]
  [ 7.3  1. ]
  [ 7.

In [160]:
# Знайти найбільш часто повторюване значення в массиві
mode = uniqs[np.argmax(count)] 
print(mode) 

0.2


In [161]:
# Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.
def func(array):
    mean = np.mean(array)
    return np.where(array < mean, 2*array, array/4)

In [162]:
# Застосувати отриману функцію до 3-ї колонки. Функція має прийняти лише одну колонку і повернути колонку із зміненими значеннями
data_combined[:, 2] = func(data_combined[:, 2])
data_combined

array([[0.   , 3.5  , 2.8  , 0.2  ],
       [4.3  , 3.   , 2.8  , 0.2  ],
       [4.4  , 3.2  , 2.6  , 0.2  ],
       [4.4  , 3.1  , 3.   , 0.2  ],
       [4.4  , 3.6  , 2.8  , 0.2  ],
       [4.5  , 3.9  , 3.4  , 0.4  ],
       [4.6  , 3.4  , 2.8  , 0.3  ],
       [4.6  , 3.4  , 3.   , 0.2  ],
       [4.6  , 2.9  , 2.8  , 0.2  ],
       [4.6  , 3.1  , 3.   , 0.1  ],
       [4.7  , 3.7  , 3.   , 0.2  ],
       [4.7  , 3.4  , 3.2  , 0.2  ],
       [4.8  , 3.   , 2.8  , 0.1  ],
       [4.8  , 3.   , 2.2  , 0.1  ],
       [4.8  , 4.   , 0.   , 0.2  ],
       [4.8  , 4.4  , 3.   , 0.4  ],
       [4.8  , 3.9  , 2.6  , 0.4  ],
       [4.9  , 3.5  , 2.8  , 0.3  ],
       [4.9  , 3.8  , 3.4  , 0.3  ],
       [4.9  , 3.8  , 3.   , 0.3  ],
       [4.9  , 3.4  , 3.4  , 0.2  ],
       [4.9  , 3.7  , 3.   , 0.4  ],
       [5.   , 3.6  , 2.   , 0.2  ],
       [5.   , 3.3  , 3.4  , 0.5  ],
       [5.   , 3.4  , 3.8  , 0.2  ],
       [5.   , 3.   , 3.2  , 0.2  ],
       [5.   , 3.4  , 3.2  , 0.4  ],
 